Remove missing re-export of "is" from ember-cli-page-object
Addepar/ember-classy-page-object pull request #46
Opened 2024-12-27 11:46 UTC by bantic

The `is` helper was removed from ember-cli-page-object in the 2.x series, and its [deprecations guide](https://ember-cli-page-object.js.org/docs/v1.17.x/deprecations) points this out:

> we no longer recommend to use is property, and plan to remove it in v2 of page objects.

![image](https://github.com/user-attachments/assets/4fb750c5-3130-4d65-8509-435dc025a181)

I noticed that this was an invalid re-export when running a a local embroider build of ember-table (which depends on this addon).

2025-01-02 15:15 UTC, mixonic requested changes

2025-01-02 15:15 UTC, mixonic commented on addon-test-support/index.js
> -  is,
I think Addepar uses this re-export in the main codebase.

2025-01-03 09:46 UTC, bantic commented on addon-test-support/index.js
> -  is,
I'll double-check, but I don't think it's possible. `import { is } from 'ember-class-page-object';` should give you an `is === undefined`

2025-01-03 09:57 UTC, bantic commented
Closing in favor of this previous PR already covers this: https://github.com/Addepar/ember-classy-page-object/pull/45

After we fix CI I'll return to that PR

2025-01-03 09:57 UTC, closed without merging